// Originally generated by urlfilter's scripts/content-script (not vendored
// here). Modified by ResultV (2026-07-16): JS cosmetic rules are emitted as
// strings and executed by applyJSRules — scriptlet rules through the
// vendored @adguard/scriptlets runtime (see scriptletsbundle.go), plain
// #%# rules via new Function. Edit directly; there is no generator in this
// repo.

package proxy

import "text/template"

const contentScript = "/* content-script v1.0.0 Sun Sep 08 2019 */\n" +
	"(function (configuration) {\n" +
	"    'use strict';\n" +
	"\n" +
	"    function getCurrentScript() {\n" +
	"        let { currentScript } = document;\n" +
	"        if (!currentScript) {\n" +
	"            const scripts = document.getElementsByTagName('script');\n" +
	"            currentScript = scripts[scripts.length - 1];\n" +
	"        }\n" +
	"        return currentScript;\n" +
	"    }\n" +
	"\n" +
	"    /**\n" +
	"     * Cosmetic rules object.\n" +
	"     *\n" +
	"     * @typedef {Object} Cosmeticresult\n" +
	"     * @property {StylesResult} elementHiding - Element hiding rules\n" +
	"     * @property {StylesResult} css - CSS rules\n" +
	"     * @property {ScriptsResult} js - JS rules\n" +
	"     */\n" +
	"\n" +
	"    /**\n" +
	"     * Styles result object\n" +
	"     *\n" +
	"     * @typedef {Object} StylesResult\n" +
	"     * @property {Array<string>} generic - Generic styles\n" +
	"     * @property {Array<string>} specific - Styles specific to this website\n" +
	"     * @property {Array<string>} genericExtCss - Generic ExtCSS styles\n" +
	"     * @property {Array<string>} specificExtCss - ExtCSS styles specific to this website\n" +
	"     */\n" +
	"\n" +
	"    /**\n" +
	"     * Scripts result object\n" +
	"     *\n" +
	"     * @typedef {Object} StylesResult\n" +
	"     * @property {Array<function>} generic - Generic functions\n" +
	"     * @property {Array<function>} specific - Functions specific to this website\n" +
	"     */\n" +
	"\n" +
	"    /**\n" +
	"     * Creates CSS rules from the cosmetic result\n" +
	"     * @param {*} rules rules\n" +
	"     * @param {*} style (optional) CSS style. For instance, `display: none`.\n" +
	"     */\n" +
	"    function getCssRules(rules, style) {\n" +
	"        const cssRules = [];\n" +
	"\n" +
	"        rules.forEach((rule) => {\n" +
	"            if (style) {\n" +
	"                cssRules.push(`${rule} { ${style} }`);\n" +
	"            } else {\n" +
	"                cssRules.push(rule);\n" +
	"            }\n" +
	"        });\n" +
	"\n" +
	"        return cssRules;\n" +
	"    }\n" +
	"\n" +
	"    /**\n" +
	"     * Creates a <style> tag that will be added to this page\n" +
	"     * @param {string} nonce - nonce string (that is added to the CSP of this page)\n" +
	"     * @param {CosmeticResult} cosmeticResult - cosmetic rules\n" +
	"     */\n" +
	"    function createStyle(nonce, cosmeticResult) {\n" +
	"        const style = document.createElement('style');\n" +
	"        style.setAttribute('nonce', nonce);\n" +
	"        style.setAttribute('type', 'text/css');\n" +
	"\n" +
	"        const cssRules = [\n" +
	"            ...getCssRules(cosmeticResult.elementHiding.generic, 'display: none!important'),\n" +
	"            ...getCssRules(cosmeticResult.elementHiding.specific, 'display: none!important'),\n" +
	"            ...getCssRules(cosmeticResult.css.generic),\n" +
	"            ...getCssRules(cosmeticResult.css.specific),\n" +
	"        ];\n" +
	"\n" +
	"        const cssTextNode = document.createTextNode(cssRules.join('\\n'));\n" +
	"        style.appendChild(cssTextNode);\n" +
	"        return style;\n" +
	"    }\n" +
	"\n" +
	"    /**\n" +
	"     * Applies cosmetic rules to the page\n" +
	"     *\n" +
	"     * @param {string} nonce - nonce string (that is added to the CSP of this page)\n" +
	"     * @param {CosmeticResult} cosmeticResult - cosmetic rules\n" +
	"     */\n" +
	"    function applyCosmeticResult(nonce, cosmeticResult) {\n" +
	"        const style = createStyle(nonce, cosmeticResult);\n" +
	"\n" +
	"        const currentScript = getCurrentScript();\n" +
	"        const rootElement = currentScript.parentNode;\n" +
	"        let insertBeforeElement = currentScript;\n" +
	"        if (currentScript.parentNode !== rootElement) {\n" +
	"            insertBeforeElement = null;\n" +
	"        }\n" +
	"        rootElement.insertBefore(style, insertBeforeElement);\n" +
	"\n" +
	"        /* Override styleEl's disabled\" property for forever enabled */\n" +
	"        const disabledDescriptor = {\n" +
	"            get: () => false,\n" +
	"            set: () => false,\n" +
	"        };\n" +
	"        Object.defineProperty(style, 'disabled', disabledDescriptor);\n" +
	"        Object.defineProperty(style.sheet, 'disabled', disabledDescriptor);\n" +
	"    }\n" +
	"\n" +
	"    /* ResultV: apply ExtendedCSS rules (:has, :contains, :matches-css,\n" +
	"       :upward, :remove, …) that a plain <style> tag cannot express. The\n" +
	"       element-hiding ExtCSS arrays are bare selectors (need a display:none\n" +
	"       declaration); the css ExtCSS arrays are already full rule text. */\n" +
	"    function applyExtendedCss(cosmeticResult) {\n" +
	"        const extCssRules = [\n" +
	"            ...getCssRules(cosmeticResult.elementHiding.genericExtCss, 'display: none!important'),\n" +
	"            ...getCssRules(cosmeticResult.elementHiding.specificExtCss, 'display: none!important'),\n" +
	"            ...getCssRules(cosmeticResult.css.genericExtCss),\n" +
	"            ...getCssRules(cosmeticResult.css.specificExtCss),\n" +
	"        ];\n" +
	"        if (extCssRules.length === 0) {\n" +
	"            return;\n" +
	"        }\n" +
	"        if (typeof ExtendedCss === 'undefined' || !ExtendedCss || typeof ExtendedCss.ExtendedCss !== 'function') {\n" +
	"            return;\n" +
	"        }\n" +
	"        const Engine = ExtendedCss.ExtendedCss;\n" +
	"        try {\n" +
	"            new Engine({ cssRules: extCssRules }).apply();\n" +
	"        } catch (e) {\n" +
	"            /* One malformed rule makes the whole batch throw; retry per-rule\n" +
	"               so the rest still apply. */\n" +
	"            extCssRules.forEach((rule) => {\n" +
	"                try {\n" +
	"                    new Engine({ cssRules: [rule] }).apply();\n" +
	"                } catch (e2) {\n" +
	"                    try { console.debug('resultv: extcss rule failed', rule, e2); } catch (e3) {}\n" +
	"                }\n" +
	"            });\n" +
	"        }\n" +
	"    }\n" +
	"\n" +
	"    /* ResultV: parse \"//scriptlet('name', 'arg')\" rule text. */\n" +
	"    function parseScriptletRule(ruleText) {\n" +
	"        const match = /^\\/\\/scriptlet\\((.*)\\)\\s*$/.exec(ruleText);\n" +
	"        if (!match) {\n" +
	"            return null;\n" +
	"        }\n" +
	"        const args = [];\n" +
	"        const re = /(['\"])((?:\\\\.|(?!\\1).)*)\\1/g;\n" +
	"        let m;\n" +
	"        while ((m = re.exec(match[1])) !== null) {\n" +
	"            args.push(m[2].replace(/\\\\(['\"])/g, '$1'));\n" +
	"        }\n" +
	"        if (args.length === 0) {\n" +
	"            return null;\n" +
	"        }\n" +
	"        return { name: args[0], args: args.slice(1) };\n" +
	"    }\n" +
	"\n" +
	"    /* ResultV: execute #%# JS rules; scriptlets need the runtime. */\n" +
	"    function applyJSRules(js) {\n" +
	"        if (!js) {\n" +
	"            return;\n" +
	"        }\n" +
	"        const all = [].concat(js.generic || [], js.specific || []);\n" +
	"        all.forEach((ruleText) => {\n" +
	"            try {\n" +
	"                const parsed = parseScriptletRule(ruleText);\n" +
	"                if (parsed) {\n" +
	"                    if (typeof scriptlets === 'undefined' || !scriptlets || typeof scriptlets.invoke !== 'function') {\n" +
	"                        return;\n" +
	"                    }\n" +
	"                    const code = scriptlets.invoke({\n" +
	"                        name: parsed.name,\n" +
	"                        args: parsed.args,\n" +
	"                        engine: 'resultv',\n" +
	"                        version: '1.0',\n" +
	"                        verbose: false,\n" +
	"                    });\n" +
	"                    if (code) {\n" +
	"                        new Function(code)();\n" +
	"                    }\n" +
	"                } else {\n" +
	"                    new Function(ruleText)();\n" +
	"                }\n" +
	"            } catch (e) {\n" +
	"                try { console.debug('resultv: js rule failed', e); } catch (e2) {}\n" +
	"            }\n" +
	"        });\n" +
	"    }\n" +
	"\n" +
	"    // eslint-disable-next-line import/no-unresolved\n" +
	"\n" +
	"    const contentScriptExecutionFlagToCheck = configuration.nonce || 'adgRunId';\n" +
	"    if (!document[contentScriptExecutionFlagToCheck]) {\n" +
	"        // content script was already executed, doing nothing\n" +
	"        document[contentScriptExecutionFlagToCheck] = true;\n" +
	"        applyCosmeticResult(configuration.nonce, configuration.cosmeticResult);\n" +
	"        applyExtendedCss(configuration.cosmeticResult);\n" +
	"        applyJSRules(configuration.cosmeticResult.js);\n" +
	"    }\n" +
	"\n" +
	"}({\n" +
	"    \"nonce\": \"{{.Nonce}}\",\n" +
	"    \"cosmeticResult\": {\n" +
	"        \"elementHiding\": {\n" +
	"            \"generic\": [\n" +
	"                {{range .Result.ElementHiding.Generic}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"            \"specific\": [\n" +
	"                {{range .Result.ElementHiding.Specific}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"            \"genericExtCss\": [\n" +
	"                {{range .Result.ElementHiding.GenericExtCSS}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"            \"specificExtCss\": [\n" +
	"                {{range .Result.ElementHiding.SpecificExtCSS}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"        },\n" +
	"        \"css\": {\n" +
	"            \"generic\": [\n" +
	"                {{range .Result.CSS.Generic}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"            \"specific\": [\n" +
	"                {{range .Result.CSS.Specific}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"            \"genericExtCss\": [\n" +
	"                {{range .Result.CSS.GenericExtCSS}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"            \"specificExtCss\": [\n" +
	"                {{range .Result.CSS.SpecificExtCSS}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"        },\n" +
	"        \"js\": {\n" +
	"            \"generic\": [\n" +
	"                {{range .Result.JS.Generic}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"            \"specific\": [\n" +
	"                {{range .Result.JS.Specific}}\"{{js .}}\",{{end}}\n" +
	"            ],\n" +
	"        }\n" +
	"    }\n" +
	"}));\n" +
	"\n"

var contentScriptTmpl = template.Must(template.New("contentScript").Parse(contentScript))
