#!/usr/bin/env python3
"""Regenerate the adaptive launcher icon layers from logo.svg.

    python scripts/gen-launcher-icon.py [shield_units]

The layers are vectors so one set serves every launcher mask (circle, squircle,
rounded square). Only the shield size is tunable; everything else is taken
verbatim from logo.svg so the icon cannot drift from the design.

shield_units is the shield's height in the adaptive icon's 108-unit layer:
  <= 51.5  fits Android's official 66dp safe circle
  <= 56.0  bounding box still inscribes in the 72dp circular mask
"""
import os
import re
import sys

SHIELD_UNITS = 48.0     # height of the shield within the 108-unit layer
SHADOW_OFFSET = 60.0    # logo.svg's feOffset dx/dy, in source coordinates
VP = 2000.0             # viewport == the full 108dp adaptive layer
UNIT = VP / 108.0

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, 'android', 'app', 'src', 'main', 'res', 'drawable')


def parse_logo(svg):
    """Pull the shield path, its bbox and the gradient stops out of logo.svg."""
    path = re.search(r'<path fill-rule="evenodd"[^>]*\sd="([^"]+)"', svg).group(1)

    # The filter region is the shield grown by the drop shadow's offset, so the
    # shield's own bbox is that region minus the offset.
    f = re.search(r'<filter id="filter0_d[^>]*x="([\d.]+)" y="([\d.]+)" '
                  r'width="([\d.]+)" height="([\d.]+)"', svg)
    fx, fy, fw, fh = map(float, f.groups())
    bbox = (fx, fy, fx + fw - SHADOW_OFFSET, fy + fh - SHADOW_OFFSET)

    # feColorMatrix -> the shadow's RGBA; it is semi-transparent and unblurred.
    m = re.search(r'<feColorMatrix type="matrix" values="([^"]+)"/>\s*<feBlend', svg)
    v = [float(x) for x in m.group(1).split()]
    shadow = '#%02X%02X%02X%02X' % (round(v[18] * 255), round(v[4] * 255),
                                    round(v[9] * 255), round(v[14] * 255))

    stops = re.findall(r'<stop(?:\s+offset="([\d.]+)")?\s*stop-color="(#[0-9A-Fa-f]{6})"/>', svg)
    stops = [(o or '0', c) for o, c in stops]
    return path, bbox, shadow, stops


def main():
    units = float(sys.argv[1]) if len(sys.argv) > 1 else SHIELD_UNITS
    with open(os.path.join(ROOT, 'logo.svg'), encoding='utf-8') as fh:
        svg = fh.read()
    path, (x0, y0, x1, y1), shadow, stops = parse_logo(svg)

    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    scale = units * UNIT / (y1 - y0)
    w_units = (x1 - x0) * scale / UNIT
    half_diag = ((units / 2) ** 2 + (w_units / 2) ** 2) ** 0.5
    print('shield %.2f x %.2f units, scale %.6f, half-diagonal %.2f '
          '(36 = circular mask, 33 = safe circle)' % (w_units, units, scale, half_diag))

    # Map the gradient onto the 72dp visible window rather than the full 108dp
    # layer, so the masked icon shows the full designed colour range.
    vis = VP * 72 / 108
    g0, g1 = (VP - vis) / 2, (VP + vis) / 2

    hdr = ('<?xml version="1.0" encoding="utf-8"?>\n'
           '<!-- Generated by scripts/gen-launcher-icon.py from logo.svg. Do not hand-edit. -->\n')
    vec = ('<vector xmlns:android="http://schemas.android.com/apk/res/android"%s\n'
           '    android:width="108dp"\n'
           '    android:height="108dp"\n'
           '    android:viewportWidth="2000"\n'
           '    android:viewportHeight="2000">\n')
    grp = ('    <group\n'
           '        android:pivotX="%g"\n'
           '        android:pivotY="%g"\n'
           '        android:scaleX="%.6f"\n'
           '        android:scaleY="%.6f"\n'
           '        android:translateX="%g"\n'
           '        android:translateY="%g">\n'
           % (cx, cy, scale, scale, VP / 2 - cx, VP / 2 - cy))
    shield = ('<path\n            android:fillColor="#FFFFFFFF"\n'
              '            android:fillType="evenOdd"\n'
              '            android:pathData="%s" />\n' % path)

    items = '\n'.join('                <item android:offset="%s" android:color="#FF%s" />'
                      % (o, c[1:]) for o, c in stops)
    write('ic_launcher_background.xml',
          hdr +
          '<!-- Brand gradient, exact stops from logo.svg, mapped onto the 72dp visible\n'
          '     window; the cropped margins clamp to the end stops. -->\n'
          + vec % ' xmlns:aapt="http://schemas.android.com/aapt"'
          + '    <path android:pathData="M0,0h2000v2000h-2000z">\n'
            '        <aapt:attr name="android:fillColor">\n'
            '            <gradient\n'
            '                android:type="linear"\n'
            '                android:startX="1000"\n'
            '                android:startY="%.2f"\n'
            '                android:endX="1000"\n'
            '                android:endY="%.2f"\n'
            '                android:tileMode="clamp">\n' % (g0, g1)
          + items + '\n'
            '            </gradient>\n        </aapt:attr>\n    </path>\n</vector>\n')

    write('ic_launcher_foreground.xml',
          hdr +
          '<!-- Shield sized to fit every launcher mask. evenOdd knocks the "r6" out so\n'
          '     the background gradient shows through. The shadow is logo.svg\'s filter:\n'
          '     the shield offset by (%g,%g) at %s, drawn under the shield. -->\n'
          % (SHADOW_OFFSET, SHADOW_OFFSET, shadow)
          + vec % '' + grp
          + '        <group android:translateX="%g" android:translateY="%g">\n'
            '            <path\n'
            '                android:fillColor="%s"\n'
            '                android:fillType="evenOdd"\n'
            '                android:pathData="%s" />\n'
            '        </group>\n' % (SHADOW_OFFSET, SHADOW_OFFSET, shadow, path)
          + '        ' + shield + '    </group>\n</vector>\n')

    write('ic_launcher_monochrome.xml',
          hdr + '<!-- Themed-icon layer: bare shield silhouette, no drop shadow. -->\n'
          + vec % '' + grp + '        ' + shield + '    </group>\n</vector>\n')


def write(name, text):
    with open(os.path.join(RES, name), 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('wrote', name)


if __name__ == '__main__':
    main()
