// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {proxy} from '../models';
import {main} from '../models';
import {logger} from '../models';
import {system} from '../models';
import {updater} from '../models';

export function AddRoutingList(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<config.RoutingList>;

export function AddSubscription(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<Array<config.ProxyEntry>>;

export function ApplyMode(arg1:string):Promise<proxy.ConnectResultDTO>;

export function CancelConnect():Promise<void>;

export function CancelUpdate():Promise<void>;

export function Connect(arg1:proxy.ProxyConfig,arg2:config.RoutingRules,arg3:boolean,arg4:boolean):Promise<proxy.ConnectResultDTO>;

export function DebugFrontendLog(arg1:string):Promise<void>;

export function DecodeDeepLink(arg1:string):Promise<string>;

export function DeleteRoutingList(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function DetectCountry(arg1:string):Promise<string>;

export function Disconnect():Promise<void>;

export function ExportConfig(arg1:string):Promise<string>;

export function FetchSubscription(arg1:string,arg2:boolean):Promise<Array<config.ProxyEntry>>;

export function GetAdBlockStatus():Promise<main.AdBlockStatusDTO>;

export function GetConfig():Promise<config.AppConfig>;

export function GetLANIPs():Promise<Array<string>>;

export function GetLeftoverRecoveryReport():Promise<Record<string, boolean>>;

export function GetLogs(arg1:number,arg2:number):Promise<logger.LogPage>;

export function GetMode():Promise<string>;

export function GetNetworkStatus():Promise<system.NetworkStatus>;

export function GetNetworkTraffic():Promise<system.TrafficStats>;

export function GetPlatform():Promise<string>;

export function GetStatus():Promise<proxy.StatusDTO>;

export function GetUpdateManifest():Promise<updater.Manifest>;

export function GetVersion():Promise<string>;

export function HandleDeepLink(arg1:string):Promise<void>;

export function ImportConfig(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function InstallAdBlockCA():Promise<void>;

export function IsAdBlockCAInstalled():Promise<boolean>;

export function IsAdmin():Promise<boolean>;

export function IsAutostartEnabled():Promise<boolean>;

export function ParseSubscriptionText(arg1:string):Promise<Array<config.ProxyEntry>>;

export function PickAppForWhitelist():Promise<string>;

export function PingProxy(arg1:string,arg2:number,arg3:string):Promise<proxy.PingResultDTO>;

export function QueueDeepLink(arg1:string):Promise<void>;

export function RefreshRoutingList(arg1:string):Promise<config.RoutingList>;

export function RefreshSubscription(arg1:string):Promise<Array<config.ProxyEntry>>;

export function ResetLeftoverReport():Promise<string>;

export function RestartAsAdmin():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetStartInTray(arg1:boolean):Promise<void>;

export function SetTrayIcon(arg1:Array<number>):Promise<void>;

export function StartMITM(arg1:number):Promise<number>;

export function StartUpdate():Promise<void>;

export function StopMITM():Promise<void>;

export function SyncProxies(arg1:Array<config.ProxyEntry>):Promise<void>;

export function ToggleAdBlock(arg1:boolean):Promise<void>;

export function ToggleKillSwitch(arg1:boolean):Promise<void>;

export function UpdateAdBlockFilters():Promise<void>;

export function UpdateRoutingList(arg1:config.RoutingList):Promise<void>;

export function UpdateRules(arg1:config.RoutingRules):Promise<void>;
