// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {proxy} from '../models';
import {logger} from '../models';
import {system} from '../models';

export function AddSubscription(arg1:string,arg2:string):Promise<Array<config.ProxyEntry>>;

export function ApplyMode(arg1:string):Promise<proxy.ConnectResultDTO>;

export function CancelConnect():Promise<void>;

export function Connect(arg1:proxy.ProxyConfig,arg2:config.RoutingRules,arg3:boolean,arg4:boolean):Promise<proxy.ConnectResultDTO>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function DetectCountry(arg1:string):Promise<string>;

export function Disconnect():Promise<void>;

export function ExportConfig():Promise<string>;

export function FetchSubscription(arg1:string):Promise<Array<config.ProxyEntry>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetLANIPs():Promise<Array<string>>;

export function GetLogs(arg1:number,arg2:number):Promise<logger.LogPage>;

export function GetMode():Promise<string>;

export function GetNetworkStatus():Promise<system.NetworkStatus>;

export function GetNetworkTraffic():Promise<system.TrafficStats>;

export function GetPlatform():Promise<string>;

export function GetStatus():Promise<proxy.StatusDTO>;

export function GetVersion():Promise<string>;

export function HandleDeepLink(arg1:string):Promise<void>;

export function ImportConfig(arg1:string):Promise<void>;

export function IsAdmin():Promise<boolean>;

export function IsAutostartEnabled():Promise<boolean>;

export function ParseSubscriptionText(arg1:string):Promise<Array<config.ProxyEntry>>;

export function PingProxy(arg1:string,arg2:number,arg3:string):Promise<proxy.PingResultDTO>;

export function QueueDeepLink(arg1:string):Promise<void>;

export function RefreshSubscription(arg1:string):Promise<Array<config.ProxyEntry>>;

export function RestartAsAdmin():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetStartInTray(arg1:boolean):Promise<void>;

export function SetTrayIcon(arg1:Array<number>):Promise<void>;

export function SyncProxies(arg1:Array<config.ProxyEntry>):Promise<void>;

export function ToggleAdBlock(arg1:boolean):Promise<void>;

export function ToggleKillSwitch(arg1:boolean):Promise<void>;

export function UpdateRules(arg1:config.RoutingRules):Promise<void>;
