// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function ApplyMode(arg1) {
  return window['go']['main']['App']['ApplyMode'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function DecryptHappLink(arg1, arg2) {
  return window['go']['main']['App']['DecryptHappLink'](arg1, arg2);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function DetectCountry(arg1) {
  return window['go']['main']['App']['DetectCountry'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function FetchSubscription(arg1) {
  return window['go']['main']['App']['FetchSubscription'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLANIPs() {
  return window['go']['main']['App']['GetLANIPs']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetNetworkTraffic() {
  return window['go']['main']['App']['GetNetworkTraffic']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsAutostartEnabled() {
  return window['go']['main']['App']['IsAutostartEnabled']();
}

export function PingProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['PingProxy'](arg1, arg2, arg3);
}

export function RefreshSubscription(arg1) {
  return window['go']['main']['App']['RefreshSubscription'](arg1);
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetStartInTray(arg1) {
  return window['go']['main']['App']['SetStartInTray'](arg1);
}

export function SetTrayIcon(arg1) {
  return window['go']['main']['App']['SetTrayIcon'](arg1);
}

export function SyncProxies(arg1) {
  return window['go']['main']['App']['SyncProxies'](arg1);
}

export function ToggleAdBlock(arg1) {
  return window['go']['main']['App']['ToggleAdBlock'](arg1);
}

export function ToggleKillSwitch(arg1) {
  return window['go']['main']['App']['ToggleKillSwitch'](arg1);
}

export function UpdateRules(arg1) {
  return window['go']['main']['App']['UpdateRules'](arg1);
}
